name: Build App

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build App and Package
    runs-on: macos-13
    timeout-minutes: 10

    env:
      commit_date_time: ${{ github.event.head_commit.timestamp }}
      repository: ${{ github.repository}}
      branch: ${{ github.ref }}
      commit_url: ${{ github.event.head_commit.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12-dev'

      - name: Install pip packages
        run: zsh Install-Dependencies.command --pip

      - name: Build App
        uses: nick-fields/retry@v2
        with:
          retry_on: timeout
          timeout_minutes: 2
          retry_wait_seconds: 0
          max_attempts: 15
          on_retry_command: zsh Clean.command
          command: python3.12 Build-App.command --date_time "${{ env.commit_date_time }}" --repository "${{ env.repository }}" --branch "${{ env.branch }}" --commit_url "${{ env.commit_url }}"

      - name: Zip App
        run: ditto -c -k --sequesterRsrc --keepParent "dist/OpenCore Legacy Patcher.app" OpenCore-Legacy-Patcher.app.zip

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore Legacy Patcher.app
          path: OpenCore-Legacy-Patcher.app.zip

      - name: Install WhiteBox Packages
        run: zsh Install-Dependencies.command --packages

      - name: Build support package
        run: packagesbuild payloads/InstallPackage/AutoPkg-Assets-Setup.pkgproj

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: AutoPkg-Assets.pkg
          path: dist/AutoPkg-Assets.pkg
